"""modify products table; add price and stock columns

Revision ID: f5b8887e4efd
Revises: 867b27b84588
Create Date: 2025-11-25 16:28:07.651456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b8887e4efd'
down_revision: Union[str, Sequence[str], None] = '867b27b84588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stock')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
